workflows:
  android-debug:
    name: Fake GPS - Debug APK
    max_build_duration: 30
    instance_type: linux
    environment:
      java: 17
    scripts:
      - name: Build debug APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
